DROP TABLE Persoane
/
CREATE TABLE Persoane 
    (PERSNO NUMBER(3) PRIMARY KEY, 
	PERSNAME CHAR(50) UNIQUE NOT NULL, 
	AGE NUMBER(2) NULL,
	JOB CHAR(50) NULL,
	INFO VARCHAR(1000) NULL
	) 
/

DROP TABLE Questions
/
CREATE TABLE Questions 
    (QUEID NUMBER(10) PRIMARY KEY, 
	QUESTION CHAR(255) UNIQUE NOT NULL, 
	TIPNAME CHAR(50) NULL,
	INFO VARCHAR(1000) NULL
	) 
/

DROP TABLE QuestionsAsked
/
CREATE TABLE QuestionsAsked 
    (PERSNAME CHAR(50) NOT NULL, 
	QUEID NUMBER(10) UNIQUE NOT NULL,
	) 
/


DROP TABLE QuestionsVersion
/
CREATE TABLE QuestionsVersion 
    (QUEVERSID NUMBER(12) PRIMARY KEY, 
	QUEID NUMBER(10) NOT NULL, 
	QUESTION CHAR(255) UNIQUE NOT NULL
	) 
/

DROP TABLE Answers
/
CREATE TABLE Answers 
    (ANSID NUMBER(12) PRIMARY KEY, 
	PERSNO NUMBER(3) NULL,
	QUEID NUMBER(10) NOT NULL,
	QUEVERSID NUMBER(12) NOT NULL,
	ANSWER CHAR(255) NOT NULL, 
	INFO VARCHAR(1000) NULL
	) 
/

DROP TABLE Tip
/
CREATE TABLE Tip 
    (TIPID NUMBER(10) PRIMARY KEY, 
	TIPNAME CHAR(50) NOT NULL,
	INFO VARCHAR(1000) NULL
	) 
/

COMMIT;